{"failed_row": {"id": 1, "email": "sheikh.sadik@habilelabs.io", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981174+00:00", "updated_at": "2024-11-26 13:19:59.981191+00:00", "organization_id": "4bc48203-7869-4786-8bc2-31bd61c90f42", "project_id": "12da2694-27cd-4dca-830e-e4849eee80e2", "user_id": "2"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(4bc48203-7869-4786-8bc2-31bd61c90f42) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(4bc48203-7869-4786-8bc2-31bd61c90f42) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 2, "email": "2017pgicsrishi036@poornima.org", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981194+00:00", "updated_at": "2024-11-26 13:19:59.981195+00:00", "organization_id": "7e661f09-a305-45e5-8332-e003cf1a2bac", "project_id": "11247567-caf0-4fa5-b2f6-29dfb7a0ce97", "user_id": "4"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(7e661f09-a305-45e5-8332-e003cf1a2bac) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(7e661f09-a305-45e5-8332-e003cf1a2bac) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 3, "email": "stvxdkxwnmukaimlpg@hthlm.com", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981197+00:00", "updated_at": "2024-11-26 13:19:59.981198+00:00", "organization_id": "025fc7c3-ff00-4d97-b5b3-6fbe866ca493", "project_id": "5d85d1c4-bf7b-42bc-a0d8-15b6d8afb092", "user_id": "5"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(025fc7c3-ff00-4d97-b5b3-6fbe866ca493) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(025fc7c3-ff00-4d97-b5b3-6fbe866ca493) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 4, "email": "stvxdkxwnmukaimlpg@hthlm.com", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981200+00:00", "updated_at": "2024-11-26 13:19:59.981201+00:00", "organization_id": "025fc7c3-ff00-4d97-b5b3-6fbe866ca493", "project_id": "5e63b9e9-4199-4b80-93d2-24d502a3b0f8", "user_id": "5"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(025fc7c3-ff00-4d97-b5b3-6fbe866ca493) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(025fc7c3-ff00-4d97-b5b3-6fbe866ca493) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 5, "email": "aashu.0704@zohomail.in", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981203+00:00", "updated_at": "2024-11-26 13:19:59.981204+00:00", "organization_id": "d6c74e6c-2039-4df2-8e68-646e262efd96", "project_id": "308e8b6b-fb8c-49fb-ae1d-9b438efc8ea7", "user_id": "6"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(d6c74e6c-2039-4df2-8e68-646e262efd96) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(d6c74e6c-2039-4df2-8e68-646e262efd96) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 6, "email": "aashu.0704@zohomail.in", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981206+00:00", "updated_at": "2024-11-26 13:19:59.981207+00:00", "organization_id": "d6c74e6c-2039-4df2-8e68-646e262efd96", "project_id": "4ea60b75-a357-45ad-9053-e6b7c12a6551", "user_id": "6"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(d6c74e6c-2039-4df2-8e68-646e262efd96) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(d6c74e6c-2039-4df2-8e68-646e262efd96) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 7, "email": "aashu.0704@zohomail.in", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981213+00:00", "updated_at": "2024-11-26 13:19:59.981214+00:00", "organization_id": "d6c74e6c-2039-4df2-8e68-646e262efd96", "project_id": "35296601-dad8-4168-b137-097489f2555e", "user_id": "6"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(d6c74e6c-2039-4df2-8e68-646e262efd96) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(d6c74e6c-2039-4df2-8e68-646e262efd96) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 8, "email": "aashu.0704@zohomail.in", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981216+00:00", "updated_at": "2024-11-26 13:19:59.981217+00:00", "organization_id": "d6c74e6c-2039-4df2-8e68-646e262efd96", "project_id": "8f392e92-73fc-40e0-8d1b-ec6330e40f2d", "user_id": "6"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(d6c74e6c-2039-4df2-8e68-646e262efd96) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(d6c74e6c-2039-4df2-8e68-646e262efd96) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 9, "email": "aashu.0704@zohomail.in", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981219+00:00", "updated_at": "2024-11-26 13:19:59.981220+00:00", "organization_id": "d6c74e6c-2039-4df2-8e68-646e262efd96", "project_id": "0e102e78-b5c8-4474-a2e2-9fda0fada19d", "user_id": "6"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(d6c74e6c-2039-4df2-8e68-646e262efd96) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(d6c74e6c-2039-4df2-8e68-646e262efd96) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 10, "email": "aashu.0704@zohomail.in", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981222+00:00", "updated_at": "2024-11-26 13:19:59.981223+00:00", "organization_id": "d6c74e6c-2039-4df2-8e68-646e262efd96", "project_id": "24c493cc-4322-44ae-a935-0aa031ea189f", "user_id": "6"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(d6c74e6c-2039-4df2-8e68-646e262efd96) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(d6c74e6c-2039-4df2-8e68-646e262efd96) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 11, "email": "aashu.0704@zohomail.in", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981225+00:00", "updated_at": "2024-11-26 13:19:59.981226+00:00", "organization_id": "d6c74e6c-2039-4df2-8e68-646e262efd96", "project_id": "3aa1b534-39e2-4ccb-b8bb-6bb4de1365e9", "user_id": "6"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(d6c74e6c-2039-4df2-8e68-646e262efd96) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(d6c74e6c-2039-4df2-8e68-646e262efd96) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 12, "email": "aashu.0704@zohomail.in", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981228+00:00", "updated_at": "2024-11-26 13:19:59.981229+00:00", "organization_id": "d6c74e6c-2039-4df2-8e68-646e262efd96", "project_id": "4830f083-0f07-49b9-8982-72e0ae682919", "user_id": "6"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(d6c74e6c-2039-4df2-8e68-646e262efd96) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(d6c74e6c-2039-4df2-8e68-646e262efd96) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 13, "email": "aashu.0704@zohomail.in", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981232+00:00", "updated_at": "2024-11-26 13:19:59.981233+00:00", "organization_id": "d6c74e6c-2039-4df2-8e68-646e262efd96", "project_id": "27f26059-d427-40af-abed-89ad80a55413", "user_id": "6"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(d6c74e6c-2039-4df2-8e68-646e262efd96) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(d6c74e6c-2039-4df2-8e68-646e262efd96) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 14, "email": "aashu.0704@zohomail.in", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981235+00:00", "updated_at": "2024-11-26 13:19:59.981236+00:00", "organization_id": "d6c74e6c-2039-4df2-8e68-646e262efd96", "project_id": "5d5c71a4-4324-47c7-8860-013981556b4e", "user_id": "6"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(d6c74e6c-2039-4df2-8e68-646e262efd96) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(d6c74e6c-2039-4df2-8e68-646e262efd96) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 15, "email": "aashu.0704@zohomail.in", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981238+00:00", "updated_at": "2024-11-26 13:19:59.981239+00:00", "organization_id": "d6c74e6c-2039-4df2-8e68-646e262efd96", "project_id": "973e4e72-8c56-4519-815d-6c87e32d0dc3", "user_id": "6"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(d6c74e6c-2039-4df2-8e68-646e262efd96) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(d6c74e6c-2039-4df2-8e68-646e262efd96) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 16, "email": "aashu.0704@zohomail.in", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981241+00:00", "updated_at": "2024-11-26 13:19:59.981242+00:00", "organization_id": "d6c74e6c-2039-4df2-8e68-646e262efd96", "project_id": "5f7ce2e6-714e-4450-be34-9841138f437f", "user_id": "6"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(d6c74e6c-2039-4df2-8e68-646e262efd96) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(d6c74e6c-2039-4df2-8e68-646e262efd96) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 17, "email": "aashu.0704@zohomail.in", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981243+00:00", "updated_at": "2024-11-26 13:19:59.981245+00:00", "organization_id": "d6c74e6c-2039-4df2-8e68-646e262efd96", "project_id": "3ae5b133-47af-4595-b51b-b0b6d662bdb7", "user_id": "6"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(d6c74e6c-2039-4df2-8e68-646e262efd96) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(d6c74e6c-2039-4df2-8e68-646e262efd96) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 18, "email": "aashu.0704@zohomail.in", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981246+00:00", "updated_at": "2024-11-26 13:19:59.981248+00:00", "organization_id": "d6c74e6c-2039-4df2-8e68-646e262efd96", "project_id": "5b9d77b4-3f70-4227-8acc-9490ff7de576", "user_id": "6"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(d6c74e6c-2039-4df2-8e68-646e262efd96) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(d6c74e6c-2039-4df2-8e68-646e262efd96) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 19, "email": "aashu.0704@zohomail.in", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981249+00:00", "updated_at": "2024-11-26 13:19:59.981250+00:00", "organization_id": "d6c74e6c-2039-4df2-8e68-646e262efd96", "project_id": "d2e09677-682f-4589-b116-4d6cd7b71827", "user_id": "6"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(d6c74e6c-2039-4df2-8e68-646e262efd96) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(d6c74e6c-2039-4df2-8e68-646e262efd96) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 20, "email": "aashu.0704@zohomail.in", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981254+00:00", "updated_at": "2024-11-26 13:19:59.981256+00:00", "organization_id": "d6c74e6c-2039-4df2-8e68-646e262efd96", "project_id": "fcb9d3d2-8f96-4df7-9732-174c291f0c14", "user_id": "6"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(d6c74e6c-2039-4df2-8e68-646e262efd96) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(d6c74e6c-2039-4df2-8e68-646e262efd96) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 21, "email": "aashu.0704@zohomail.in", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981258+00:00", "updated_at": "2024-11-26 13:19:59.981259+00:00", "organization_id": "d6c74e6c-2039-4df2-8e68-646e262efd96", "project_id": "9597d6cb-f53e-4858-a3e7-bd4a2a538557", "user_id": "6"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(d6c74e6c-2039-4df2-8e68-646e262efd96) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(d6c74e6c-2039-4df2-8e68-646e262efd96) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 22, "email": "aashu.0704@zohomail.in", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981260+00:00", "updated_at": "2024-11-26 13:19:59.981262+00:00", "organization_id": "d6c74e6c-2039-4df2-8e68-646e262efd96", "project_id": "456ff395-822a-4b0d-aecf-8a137d6af350", "user_id": "6"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(d6c74e6c-2039-4df2-8e68-646e262efd96) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(d6c74e6c-2039-4df2-8e68-646e262efd96) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 23, "email": "aashu.0704@zohomail.in", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981263+00:00", "updated_at": "2024-11-26 13:19:59.981264+00:00", "organization_id": "d6c74e6c-2039-4df2-8e68-646e262efd96", "project_id": "f8ff8e4a-3d92-40e0-86f2-72c18143af87", "user_id": "6"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(d6c74e6c-2039-4df2-8e68-646e262efd96) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(d6c74e6c-2039-4df2-8e68-646e262efd96) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 24, "email": "reena@habilelabs.io", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981266+00:00", "updated_at": "2024-11-26 13:19:59.981267+00:00", "organization_id": "b95880d5-82ba-4b2c-bcb5-fd8ceb53eb53", "project_id": "f15ef496-508d-4535-9abe-8be9c63af7e3", "user_id": "25"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(b95880d5-82ba-4b2c-bcb5-fd8ceb53eb53) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(b95880d5-82ba-4b2c-bcb5-fd8ceb53eb53) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 25, "email": "shubh.patiyat@habilelabs.io", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981269+00:00", "updated_at": "2024-11-26 13:19:59.981270+00:00", "organization_id": "161763cb-3f85-453d-a956-8badd08e5779", "project_id": "23800a4a-4cfa-4369-85dc-a29aee040cd3", "user_id": "11"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(161763cb-3f85-453d-a956-8badd08e5779) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(161763cb-3f85-453d-a956-8badd08e5779) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 26, "email": "ankita11habilelabs@gmail.com", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981272+00:00", "updated_at": "2024-11-26 13:19:59.981273+00:00", "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "project_id": "645a26e2-393b-48be-b259-fe5d8e8462dd", "user_id": "12"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 27, "email": "ankita11habilelabs@gmail.com", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981275+00:00", "updated_at": "2024-11-26 13:19:59.981276+00:00", "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "project_id": "75f46d28-0b8f-4aee-9659-393443253c2d", "user_id": "12"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 28, "email": "ankita11habilelabs@gmail.com", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981278+00:00", "updated_at": "2024-11-26 13:19:59.981279+00:00", "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "project_id": "70ebc58e-afc9-42b9-8120-5d0032e76958", "user_id": "12"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 29, "email": "ankita11habilelabs@gmail.com", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981280+00:00", "updated_at": "2024-11-26 13:19:59.981282+00:00", "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "project_id": "74029e99-0295-46db-b7b6-4c01fd78f47a", "user_id": "12"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 30, "email": "ankita11habilelabs@gmail.com", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981283+00:00", "updated_at": "2024-11-26 13:19:59.981285+00:00", "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "project_id": "b02d7b8d-88bf-45b9-9cd8-3a36363c9d1c", "user_id": "12"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 31, "email": "ankita11habilelabs@gmail.com", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981286+00:00", "updated_at": "2024-11-26 13:19:59.981287+00:00", "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "project_id": "31889584-055b-4bb7-9a89-2ff6f814fc72", "user_id": "12"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 32, "email": "ankita11habilelabs@gmail.com", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981289+00:00", "updated_at": "2024-11-26 13:19:59.981290+00:00", "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "project_id": "1ddac4f2-c6c7-46a2-9598-b459998cd172", "user_id": "12"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 33, "email": "ankita11habilelabs@gmail.com", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981292+00:00", "updated_at": "2024-11-26 13:19:59.981293+00:00", "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "project_id": "76818729-5139-4c86-aadb-1686e0aac597", "user_id": "12"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 34, "email": "ankita11habilelabs@gmail.com", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981296+00:00", "updated_at": "2024-11-26 13:19:59.981299+00:00", "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "project_id": "3ee7bf57-8f7c-49dc-b451-b605d8e6467c", "user_id": "12"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 35, "email": "ankita11habilelabs@gmail.com", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981301+00:00", "updated_at": "2024-11-26 13:19:59.981302+00:00", "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "project_id": "e4c14e2e-0f10-4536-ade7-f63b17a2c3dd", "user_id": "12"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 36, "email": "ankita11habilelabs@gmail.com", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981304+00:00", "updated_at": "2024-11-26 13:19:59.981305+00:00", "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "project_id": "dabda632-14d4-4f4e-b618-241c81b7cd7c", "user_id": "12"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 37, "email": "ankita11habilelabs@gmail.com", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981308+00:00", "updated_at": "2024-11-26 13:19:59.981309+00:00", "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "project_id": "09d68fc4-e0d3-45ef-986e-902399144327", "user_id": "12"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 38, "email": "ankita11habilelabs@gmail.com", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981311+00:00", "updated_at": "2024-11-26 13:19:59.981312+00:00", "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "project_id": "14e3d336-c33e-4c2c-982c-c66130f58d28", "user_id": "12"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 39, "email": "ankita11habilelabs@gmail.com", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981314+00:00", "updated_at": "2024-11-26 13:19:59.981315+00:00", "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "project_id": "29df3c37-7ac0-4ef6-9af3-746e5f3396f9", "user_id": "12"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 40, "email": "ankita11habilelabs@gmail.com", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981317+00:00", "updated_at": "2024-11-26 13:19:59.981318+00:00", "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "project_id": "118b3a23-1fc4-4435-a28c-d06476f30477", "user_id": "12"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 41, "email": "ankita11habilelabs@gmail.com", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981320+00:00", "updated_at": "2024-11-26 13:19:59.981321+00:00", "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "project_id": "7beacc91-6a98-4f2c-97f4-e4fcd4ed0743", "user_id": "12"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 42, "email": "ankita11habilelabs@gmail.com", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981323+00:00", "updated_at": "2024-11-26 13:19:59.981324+00:00", "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "project_id": "4c090d6c-791e-4f38-8618-939c5e891d42", "user_id": "12"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 43, "email": "ankita11habilelabs@gmail.com", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981325+00:00", "updated_at": "2024-11-26 13:19:59.981327+00:00", "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "project_id": "df7583e9-3b86-48d7-8bef-3dc08343fd54", "user_id": "12"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 44, "email": "ankita11habilelabs@gmail.com", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981328+00:00", "updated_at": "2024-11-26 13:19:59.981330+00:00", "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "project_id": "91e172f0-eaba-4a3e-96d5-8508b8f3eefc", "user_id": "12"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 45, "email": "ankita11habilelabs@gmail.com", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981331+00:00", "updated_at": "2024-11-26 13:19:59.981333+00:00", "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "project_id": "7bc50b8c-0d91-41d7-adf3-bbb0b83d7a95", "user_id": "12"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 46, "email": "ankita11habilelabs@gmail.com", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981334+00:00", "updated_at": "2024-11-26 13:19:59.981336+00:00", "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "project_id": "bc44e066-533f-4daf-980b-a0b98dc3bac2", "user_id": "12"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 47, "email": "ankita11habilelabs@gmail.com", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981339+00:00", "updated_at": "2024-11-26 13:19:59.981340+00:00", "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "project_id": "e8d96c8c-175c-4b12-a51d-63895b414607", "user_id": "12"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 48, "email": "ankita11habilelabs@gmail.com", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981342+00:00", "updated_at": "2024-11-26 13:19:59.981343+00:00", "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "project_id": "8a03230d-b050-4342-aa1a-9055913174c5", "user_id": "12"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 49, "email": "ankita11habilelabs@gmail.com", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981345+00:00", "updated_at": "2024-11-26 13:19:59.981346+00:00", "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "project_id": "f8dcefb2-e324-45ff-b936-f301a4c8a513", "user_id": "12"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 50, "email": "ankita11habilelabs@gmail.com", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981348+00:00", "updated_at": "2024-11-26 13:19:59.981349+00:00", "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "project_id": "d6d96249-e042-438d-8f11-84959df44137", "user_id": "12"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 51, "email": "ankita11habilelabs@gmail.com", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981350+00:00", "updated_at": "2024-11-26 13:19:59.981352+00:00", "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "project_id": "21106ee3-fd05-4056-bb46-b025825ce36b", "user_id": "12"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 52, "email": "ankita11habilelabs@gmail.com", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981354+00:00", "updated_at": "2024-11-26 13:19:59.981355+00:00", "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "project_id": "d9b16a63-a0d5-4024-b026-78a80b44db50", "user_id": "12"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 53, "email": "ankita11habilelabs@gmail.com", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981356+00:00", "updated_at": "2024-11-26 13:19:59.981358+00:00", "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "project_id": "b3aa247c-61f6-4f1a-8528-3d09aa7da3b9", "user_id": "12"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 54, "email": "ankita11habilelabs@gmail.com", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981359+00:00", "updated_at": "2024-11-26 13:19:59.981361+00:00", "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "project_id": "d22e94d5-4421-49af-8de5-cd70406b17fe", "user_id": "12"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 55, "email": "ankita11habilelabs@gmail.com", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981362+00:00", "updated_at": "2024-11-26 13:19:59.981364+00:00", "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "project_id": "fee7437a-c195-4b5d-9a33-92ae403b66a5", "user_id": "12"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 56, "email": "ankita11habilelabs@gmail.com", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981367+00:00", "updated_at": "2024-11-26 13:19:59.981368+00:00", "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "project_id": "de8fcfe1-605a-4dac-92f4-ebaa06a0f5d3", "user_id": "12"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 57, "email": "ankita11habilelabs@gmail.com", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981370+00:00", "updated_at": "2024-11-26 13:19:59.981371+00:00", "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "project_id": "f2799dff-f487-462b-a35f-18edb50408e6", "user_id": "12"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 58, "email": "ankita11habilelabs@gmail.com", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981373+00:00", "updated_at": "2024-11-26 13:19:59.981375+00:00", "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "project_id": "aafc67d5-1b25-4215-ad28-122717ac8b63", "user_id": "12"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 59, "email": "ankita11habilelabs@gmail.com", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981377+00:00", "updated_at": "2024-11-26 13:19:59.981379+00:00", "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "project_id": "2f8bd322-87b9-4153-8b77-2230eaca9dd1", "user_id": "12"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 60, "email": "ankita11habilelabs@gmail.com", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981381+00:00", "updated_at": "2024-11-26 13:19:59.981383+00:00", "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "project_id": "87d9e40c-dae8-475e-b9d8-5c2e2623f492", "user_id": "12"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 61, "email": "ankita11habilelabs@gmail.com", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981385+00:00", "updated_at": "2024-11-26 13:19:59.981386+00:00", "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "project_id": "4250ab9d-47b2-4f19-b37f-835d12628d10", "user_id": "12"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 62, "email": "ankita11habilelabs@gmail.com", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981387+00:00", "updated_at": "2024-11-26 13:19:59.981389+00:00", "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "project_id": "d1d8b2c7-edd4-43dc-a569-155e9d382e4c", "user_id": "12"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 63, "email": "ankita11habilelabs@gmail.com", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981390+00:00", "updated_at": "2024-11-26 13:19:59.981392+00:00", "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "project_id": "68d88e8e-9c24-448b-b962-f7f33585c14d", "user_id": "12"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 64, "email": "ankita11habilelabs@gmail.com", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981393+00:00", "updated_at": "2024-11-26 13:19:59.981395+00:00", "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "project_id": "1a1b45ac-7898-4574-99a0-665ef9e85811", "user_id": "12"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 65, "email": "ankita11habilelabs@gmail.com", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981396+00:00", "updated_at": "2024-11-26 13:19:59.981398+00:00", "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "project_id": "66dab4dc-387d-41cb-99a7-77611564c660", "user_id": "12"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 66, "email": "ankita11habilelabs@gmail.com", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981399+00:00", "updated_at": "2024-11-26 13:19:59.981401+00:00", "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "project_id": "e736fa69-07af-4292-9d70-85ce05704116", "user_id": "12"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 67, "email": "ankita11habilelabs@gmail.com", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981402+00:00", "updated_at": "2024-11-26 13:19:59.981404+00:00", "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "project_id": "b5f84273-aed8-4be1-b922-41894c1e43af", "user_id": "12"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 68, "email": "ankita11habilelabs@gmail.com", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981405+00:00", "updated_at": "2024-11-26 13:19:59.981407+00:00", "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "project_id": "7ffc9bb5-8b8a-4f5c-aa16-51baea29947f", "user_id": "12"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 69, "email": "ankita11habilelabs@gmail.com", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981408+00:00", "updated_at": "2024-11-26 13:19:59.981410+00:00", "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "project_id": "609c99d4-e50b-46cf-9c1d-08c0f895839d", "user_id": "12"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 70, "email": "ankita11habilelabs@gmail.com", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981411+00:00", "updated_at": "2024-11-26 13:19:59.981412+00:00", "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "project_id": "ad4e890d-ffdd-45ed-b0be-b6e8b5d1a988", "user_id": "12"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 71, "email": "ankita11habilelabs@gmail.com", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981414+00:00", "updated_at": "2024-11-26 13:19:59.981415+00:00", "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "project_id": "eb014bd1-690c-497e-b991-fba37c07eb86", "user_id": "12"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 72, "email": "ankita11habilelabs@gmail.com", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981417+00:00", "updated_at": "2024-11-26 13:19:59.981418+00:00", "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "project_id": "66059159-6f36-4a60-92ae-d48b90106e82", "user_id": "12"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 73, "email": "ankita11habilelabs@gmail.com", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981421+00:00", "updated_at": "2024-11-26 13:19:59.981423+00:00", "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "project_id": "d37f7477-b8f6-43f3-8273-6db276d7912d", "user_id": "12"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 74, "email": "ankita11habilelabs@gmail.com", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981424+00:00", "updated_at": "2024-11-26 13:19:59.981425+00:00", "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "project_id": "0ff47689-e505-45f7-9773-11149e3c7593", "user_id": "12"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 75, "email": "ankita11habilelabs@gmail.com", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981427+00:00", "updated_at": "2024-11-26 13:19:59.981428+00:00", "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "project_id": "3f6ed5dc-7325-4628-b2b4-98abb10acbd6", "user_id": "12"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 76, "email": "ankita11habilelabs@gmail.com", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981430+00:00", "updated_at": "2024-11-26 13:19:59.981431+00:00", "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "project_id": "f77b5f97-ad1b-43b0-b35e-6bc2aa67ad8d", "user_id": "12"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 77, "email": "ankita11habilelabs@gmail.com", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981434+00:00", "updated_at": "2024-11-26 13:19:59.981436+00:00", "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "project_id": "54e29b12-baea-4135-834d-0dde4dfa8e2d", "user_id": "12"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 78, "email": "ankita11habilelabs@gmail.com", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981438+00:00", "updated_at": "2024-11-26 13:19:59.981439+00:00", "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "project_id": "afc27c4b-0b4d-4471-989e-7b6256948259", "user_id": "12"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 79, "email": "ankita11habilelabs@gmail.com", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981441+00:00", "updated_at": "2024-11-26 13:19:59.981443+00:00", "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "project_id": "c5506989-db87-48fe-994c-4460ebfb6178", "user_id": "12"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 80, "email": "ankita11habilelabs@gmail.com", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981445+00:00", "updated_at": "2024-11-26 13:19:59.981446+00:00", "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "project_id": "fc37ad43-91d6-426a-9bd3-1e4598539915", "user_id": "12"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 81, "email": "ankita11habilelabs@gmail.com", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981448+00:00", "updated_at": "2024-11-26 13:19:59.981450+00:00", "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "project_id": "e40bc2bb-0262-4e0c-8908-b5d9397291d3", "user_id": "12"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 82, "email": "ankita11habilelabs@gmail.com", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981451+00:00", "updated_at": "2024-11-26 13:19:59.981453+00:00", "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "project_id": "b06e9351-df35-4213-8e36-270de121beae", "user_id": "12"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(a8141b4d-02e4-45cf-b703-e3099ba82c10) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 83, "email": "svc27669@inohm.com", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981454+00:00", "updated_at": "2024-11-26 13:19:59.981456+00:00", "organization_id": "1ace4a6c-2f48-487c-b25e-0a1d73464581", "project_id": "13e52a48-f121-42c7-80e1-c4080ad2893f", "user_id": "16"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(1ace4a6c-2f48-487c-b25e-0a1d73464581) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(1ace4a6c-2f48-487c-b25e-0a1d73464581) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 84, "email": "nimish123@mailinator.com", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981457+00:00", "updated_at": "2024-11-26 13:19:59.981458+00:00", "organization_id": "9ddfa434-ec7f-46ae-9e08-b8d88cb8ee0f", "project_id": "e0f79166-e54e-45a3-aa24-718a8838c34d", "user_id": "17"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(9ddfa434-ec7f-46ae-9e08-b8d88cb8ee0f) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(9ddfa434-ec7f-46ae-9e08-b8d88cb8ee0f) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 85, "email": "jk1282002@gmail.com", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981460+00:00", "updated_at": "2024-11-26 13:19:59.981461+00:00", "organization_id": "f1bbc8fa-0021-4b7b-861f-25bd3a19e890", "project_id": "8d2d8d96-2a91-4ca8-9497-7dcc1093e80b", "user_id": "19"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(f1bbc8fa-0021-4b7b-861f-25bd3a19e890) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(f1bbc8fa-0021-4b7b-861f-25bd3a19e890) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 86, "email": "jk1282002@gmail.com", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981463+00:00", "updated_at": "2024-11-26 13:19:59.981464+00:00", "organization_id": "f1bbc8fa-0021-4b7b-861f-25bd3a19e890", "project_id": "0568805a-633a-40da-8dcb-e5ab49bf8604", "user_id": "19"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(f1bbc8fa-0021-4b7b-861f-25bd3a19e890) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(f1bbc8fa-0021-4b7b-861f-25bd3a19e890) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 87, "email": "jk1282002@gmail.com", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981467+00:00", "updated_at": "2024-11-26 13:19:59.981468+00:00", "organization_id": "f1bbc8fa-0021-4b7b-861f-25bd3a19e890", "project_id": "f6d56870-26e1-4bf1-97cf-b7eececf1699", "user_id": "19"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(f1bbc8fa-0021-4b7b-861f-25bd3a19e890) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(f1bbc8fa-0021-4b7b-861f-25bd3a19e890) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 88, "email": "jk1282002@gmail.com", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981470+00:00", "updated_at": "2024-11-26 13:19:59.981471+00:00", "organization_id": "f1bbc8fa-0021-4b7b-861f-25bd3a19e890", "project_id": "e650d79d-4a52-4bab-b140-60ad74332313", "user_id": "19"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(f1bbc8fa-0021-4b7b-861f-25bd3a19e890) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(f1bbc8fa-0021-4b7b-861f-25bd3a19e890) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 89, "email": "jk1282002@gmail.com", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981473+00:00", "updated_at": "2024-11-26 13:19:59.981474+00:00", "organization_id": "f1bbc8fa-0021-4b7b-861f-25bd3a19e890", "project_id": "3f91a1b6-fdbc-4d4a-bbae-bc005bd4c917", "user_id": "19"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(f1bbc8fa-0021-4b7b-861f-25bd3a19e890) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(f1bbc8fa-0021-4b7b-861f-25bd3a19e890) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 90, "email": "a21kanjolia@gmail.com", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981476+00:00", "updated_at": "2024-11-26 13:19:59.981477+00:00", "organization_id": "29d9a918-9e5f-4f69-96fa-e212305c1b31", "project_id": "b1599884-7426-423e-8047-a3ff18645063", "user_id": "21"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(29d9a918-9e5f-4f69-96fa-e212305c1b31) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(29d9a918-9e5f-4f69-96fa-e212305c1b31) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 91, "email": "a21kanjolia@gmail.com", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981479+00:00", "updated_at": "2024-11-26 13:19:59.981480+00:00", "organization_id": "29d9a918-9e5f-4f69-96fa-e212305c1b31", "project_id": "789fa1cd-5231-4014-89fe-106438d2830b", "user_id": "21"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(29d9a918-9e5f-4f69-96fa-e212305c1b31) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(29d9a918-9e5f-4f69-96fa-e212305c1b31) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 92, "email": "a21kanjolia@gmail.com", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981482+00:00", "updated_at": "2024-11-26 13:19:59.981483+00:00", "organization_id": "29d9a918-9e5f-4f69-96fa-e212305c1b31", "project_id": "bad672d3-3b09-4627-b79b-c8b1baa582ca", "user_id": "21"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(29d9a918-9e5f-4f69-96fa-e212305c1b31) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(29d9a918-9e5f-4f69-96fa-e212305c1b31) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 93, "email": "a21kanjolia@gmail.com", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981485+00:00", "updated_at": "2024-11-26 13:19:59.981486+00:00", "organization_id": "29d9a918-9e5f-4f69-96fa-e212305c1b31", "project_id": "550ef7b1-8672-44f9-8629-8c58b075d286", "user_id": "21"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(29d9a918-9e5f-4f69-96fa-e212305c1b31) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(29d9a918-9e5f-4f69-96fa-e212305c1b31) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 94, "email": "a21kanjolia@gmail.com", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981488+00:00", "updated_at": "2024-11-26 13:19:59.981489+00:00", "organization_id": "29d9a918-9e5f-4f69-96fa-e212305c1b31", "project_id": "bd63006a-b632-4952-84ab-ffc93a75b385", "user_id": "21"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(29d9a918-9e5f-4f69-96fa-e212305c1b31) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(29d9a918-9e5f-4f69-96fa-e212305c1b31) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 95, "email": "a21kanjolia@gmail.com", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981491+00:00", "updated_at": "2024-11-26 13:19:59.981492+00:00", "organization_id": "29d9a918-9e5f-4f69-96fa-e212305c1b31", "project_id": "d8535855-6e08-4aa6-9354-3d0932af69df", "user_id": "21"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(29d9a918-9e5f-4f69-96fa-e212305c1b31) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(29d9a918-9e5f-4f69-96fa-e212305c1b31) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 96, "email": "a21kanjolia@gmail.com", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981494+00:00", "updated_at": "2024-11-26 13:19:59.981495+00:00", "organization_id": "29d9a918-9e5f-4f69-96fa-e212305c1b31", "project_id": "c7910682-6edd-4d18-8715-64817285ffbc", "user_id": "21"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(29d9a918-9e5f-4f69-96fa-e212305c1b31) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(29d9a918-9e5f-4f69-96fa-e212305c1b31) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 97, "email": "a21kanjolia@gmail.com", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981497+00:00", "updated_at": "2024-11-26 13:19:59.981498+00:00", "organization_id": "29d9a918-9e5f-4f69-96fa-e212305c1b31", "project_id": "9f51daf5-08ae-4377-935f-3726a1c67aa5", "user_id": "21"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(29d9a918-9e5f-4f69-96fa-e212305c1b31) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(29d9a918-9e5f-4f69-96fa-e212305c1b31) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 98, "email": "a21kanjolia@gmail.com", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981501+00:00", "updated_at": "2024-11-26 13:19:59.981502+00:00", "organization_id": "29d9a918-9e5f-4f69-96fa-e212305c1b31", "project_id": "8eb05c0f-fb27-4296-b604-fbea8e200ed8", "user_id": "21"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(29d9a918-9e5f-4f69-96fa-e212305c1b31) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(29d9a918-9e5f-4f69-96fa-e212305c1b31) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 99, "email": "a21kanjolia@gmail.com", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981504+00:00", "updated_at": "2024-11-26 13:19:59.981505+00:00", "organization_id": "29d9a918-9e5f-4f69-96fa-e212305c1b31", "project_id": "418b2598-d585-492b-b1f2-deb40473dac9", "user_id": "21"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(29d9a918-9e5f-4f69-96fa-e212305c1b31) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(29d9a918-9e5f-4f69-96fa-e212305c1b31) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 100, "email": "a21kanjolia@gmail.com", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981512+00:00", "updated_at": "2024-11-26 13:19:59.981514+00:00", "organization_id": "29d9a918-9e5f-4f69-96fa-e212305c1b31", "project_id": "26ccc49f-c894-40af-b1f9-50345b40b9b0", "user_id": "21"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(29d9a918-9e5f-4f69-96fa-e212305c1b31) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(29d9a918-9e5f-4f69-96fa-e212305c1b31) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 101, "email": "a21kanjolia@gmail.com", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981515+00:00", "updated_at": "2024-11-26 13:19:59.981517+00:00", "organization_id": "29d9a918-9e5f-4f69-96fa-e212305c1b31", "project_id": "dc0221f0-b531-492e-9c2e-6742794a6bee", "user_id": "21"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(29d9a918-9e5f-4f69-96fa-e212305c1b31) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(29d9a918-9e5f-4f69-96fa-e212305c1b31) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 102, "email": "a21kanjolia@gmail.com", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981520+00:00", "updated_at": "2024-11-26 13:19:59.981521+00:00", "organization_id": "29d9a918-9e5f-4f69-96fa-e212305c1b31", "project_id": "aa23ecc6-c28d-48e8-ad49-1edb2edc514a", "user_id": "21"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(29d9a918-9e5f-4f69-96fa-e212305c1b31) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(29d9a918-9e5f-4f69-96fa-e212305c1b31) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 103, "email": "a21kanjolia@gmail.com", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981523+00:00", "updated_at": "2024-11-26 13:19:59.981524+00:00", "organization_id": "29d9a918-9e5f-4f69-96fa-e212305c1b31", "project_id": "f92c8183-127f-48c9-b3d0-adc7aa308691", "user_id": "21"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(29d9a918-9e5f-4f69-96fa-e212305c1b31) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(29d9a918-9e5f-4f69-96fa-e212305c1b31) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 104, "email": "a21kanjolia@gmail.com", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981526+00:00", "updated_at": "2024-11-26 13:19:59.981527+00:00", "organization_id": "29d9a918-9e5f-4f69-96fa-e212305c1b31", "project_id": "14ec1013-7374-4794-979d-e60b87355054", "user_id": "21"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(29d9a918-9e5f-4f69-96fa-e212305c1b31) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(29d9a918-9e5f-4f69-96fa-e212305c1b31) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 105, "email": "a21kanjolia@gmail.com", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981529+00:00", "updated_at": "2024-11-26 13:19:59.981530+00:00", "organization_id": "29d9a918-9e5f-4f69-96fa-e212305c1b31", "project_id": "9f8fd4ea-03b9-4ce4-b28f-6b244764ead4", "user_id": "21"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(29d9a918-9e5f-4f69-96fa-e212305c1b31) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(29d9a918-9e5f-4f69-96fa-e212305c1b31) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 106, "email": "a21kanjolia@gmail.com", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981532+00:00", "updated_at": "2024-11-26 13:19:59.981533+00:00", "organization_id": "29d9a918-9e5f-4f69-96fa-e212305c1b31", "project_id": "d116f08c-dc86-42b9-b307-1c358090e3a6", "user_id": "21"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(29d9a918-9e5f-4f69-96fa-e212305c1b31) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(29d9a918-9e5f-4f69-96fa-e212305c1b31) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 107, "email": "a21kanjolia@gmail.com", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981535+00:00", "updated_at": "2024-11-26 13:19:59.981536+00:00", "organization_id": "29d9a918-9e5f-4f69-96fa-e212305c1b31", "project_id": "38854364-9bef-4f21-872a-dd85ce4f053c", "user_id": "21"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(29d9a918-9e5f-4f69-96fa-e212305c1b31) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(29d9a918-9e5f-4f69-96fa-e212305c1b31) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 108, "email": "a21kanjolia@gmail.com", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981538+00:00", "updated_at": "2024-11-26 13:19:59.981539+00:00", "organization_id": "29d9a918-9e5f-4f69-96fa-e212305c1b31", "project_id": "0d006822-2a92-484e-8485-bcc69dfe2234", "user_id": "21"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(29d9a918-9e5f-4f69-96fa-e212305c1b31) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(29d9a918-9e5f-4f69-96fa-e212305c1b31) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 109, "email": "hqw70550@dcobe.com", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981541+00:00", "updated_at": "2024-11-26 13:19:59.981542+00:00", "organization_id": "64821904-8f06-40f1-bda2-8d0420d3ac07", "project_id": "96f05839-0a7e-4212-a698-131da50d5f5e", "user_id": "23"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(64821904-8f06-40f1-bda2-8d0420d3ac07) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(64821904-8f06-40f1-bda2-8d0420d3ac07) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 110, "email": "gopesh.mathur@habilelabs.io", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981544+00:00", "updated_at": "2024-11-26 13:19:59.981545+00:00", "organization_id": "8330fa46-79d9-4d6a-a66e-589a96da3f73", "project_id": "2cae39b3-8650-4320-a0b2-8a7d6f439c4d", "user_id": "28"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(8330fa46-79d9-4d6a-a66e-589a96da3f73) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(8330fa46-79d9-4d6a-a66e-589a96da3f73) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 111, "email": "duttrishi72@gmail.com", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981547+00:00", "updated_at": "2024-11-26 13:19:59.981548+00:00", "organization_id": "38404b0b-776e-458b-b7a9-4298ca30f73e", "project_id": "2e3f241d-7754-49cd-aa56-ad15e42066e9", "user_id": "29"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(38404b0b-776e-458b-b7a9-4298ca30f73e) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(38404b0b-776e-458b-b7a9-4298ca30f73e) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 112, "email": "lesaj68451@inikale.com", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981550+00:00", "updated_at": "2024-11-26 13:19:59.981551+00:00", "organization_id": "faa4d6b0-463f-4700-ba73-a8b8e309fc0d", "project_id": "c2a60a34-795b-4b3c-a3a6-3bf5a32a7de2", "user_id": "30"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(faa4d6b0-463f-4700-ba73-a8b8e309fc0d) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(faa4d6b0-463f-4700-ba73-a8b8e309fc0d) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 113, "email": "u6cotl+7ixooy8imcua8@sharklasers.com", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981555+00:00", "updated_at": "2024-11-26 13:19:59.981557+00:00", "organization_id": "248ae295-b3ba-442e-9b66-98eb6abf905b", "project_id": "71767017-de77-46f8-ac38-b1ef15815573", "user_id": "31"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(248ae295-b3ba-442e-9b66-98eb6abf905b) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(248ae295-b3ba-442e-9b66-98eb6abf905b) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 114, "email": "wakexat100@gianes.com", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981558+00:00", "updated_at": "2024-11-26 13:19:59.981559+00:00", "organization_id": "311e736b-d415-4234-b373-5e0284ac7fc6", "project_id": "b179802e-d808-43e5-9ab6-3a2a6ceebfcc", "user_id": "32"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(311e736b-d415-4234-b373-5e0284ac7fc6) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(311e736b-d415-4234-b373-5e0284ac7fc6) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 115, "email": "shreya@habilelabs.io", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981561+00:00", "updated_at": "2024-11-26 13:19:59.981562+00:00", "organization_id": "110c33af-d8ea-4749-94f9-97b7525c9479", "project_id": "7f222789-50b9-4845-9a71-0f07d0e5ad35", "user_id": "33"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(110c33af-d8ea-4749-94f9-97b7525c9479) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(110c33af-d8ea-4749-94f9-97b7525c9479) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 116, "email": "shreya@habilelabs.io", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981564+00:00", "updated_at": "2024-11-26 13:19:59.981565+00:00", "organization_id": "110c33af-d8ea-4749-94f9-97b7525c9479", "project_id": "d88e76d4-d6d8-49a8-874c-887da1b48308", "user_id": "33"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(110c33af-d8ea-4749-94f9-97b7525c9479) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(110c33af-d8ea-4749-94f9-97b7525c9479) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 117, "email": "deepak.kumar@habilelabs.io", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981567+00:00", "updated_at": "2024-11-26 13:19:59.981568+00:00", "organization_id": "8081574f-0b2a-469f-86e7-a5be7f27c87a", "project_id": "ed16e994-81ca-45f2-a2ff-6a02f218b2bb", "user_id": "34"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(8081574f-0b2a-469f-86e7-a5be7f27c87a) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(8081574f-0b2a-469f-86e7-a5be7f27c87a) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 118, "email": "deepak.kumar@habilelabs.io", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981570+00:00", "updated_at": "2024-11-26 13:19:59.981571+00:00", "organization_id": "8081574f-0b2a-469f-86e7-a5be7f27c87a", "project_id": "f9605dd3-73b8-4586-98ca-9035da78a34e", "user_id": "34"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(8081574f-0b2a-469f-86e7-a5be7f27c87a) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(8081574f-0b2a-469f-86e7-a5be7f27c87a) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 119, "email": "deepak.kumar@habilelabs.io", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981573+00:00", "updated_at": "2024-11-26 13:19:59.981575+00:00", "organization_id": "8081574f-0b2a-469f-86e7-a5be7f27c87a", "project_id": "7ec6a73f-ac5f-40c7-9296-9515adcee3f1", "user_id": "34"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(8081574f-0b2a-469f-86e7-a5be7f27c87a) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(8081574f-0b2a-469f-86e7-a5be7f27c87a) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 120, "email": "deepak.kumar@habilelabs.io", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981577+00:00", "updated_at": "2024-11-26 13:19:59.981578+00:00", "organization_id": "8081574f-0b2a-469f-86e7-a5be7f27c87a", "project_id": "4a9199c9-4243-4d91-ab24-b867b90ae8bf", "user_id": "34"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(8081574f-0b2a-469f-86e7-a5be7f27c87a) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(8081574f-0b2a-469f-86e7-a5be7f27c87a) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 121, "email": "deepak.kumar@habilelabs.io", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981580+00:00", "updated_at": "2024-11-26 13:19:59.981581+00:00", "organization_id": "8081574f-0b2a-469f-86e7-a5be7f27c87a", "project_id": "96a60048-54c2-451d-9e50-76ac5a01d1a3", "user_id": "34"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(8081574f-0b2a-469f-86e7-a5be7f27c87a) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(8081574f-0b2a-469f-86e7-a5be7f27c87a) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 122, "email": "bjs13833@kisoq.com", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981583+00:00", "updated_at": "2024-11-26 13:19:59.981584+00:00", "organization_id": "d522bf11-71f1-4cf9-b0a2-e4451b5e3e30", "project_id": "19c3bf0a-b541-49c9-9a15-f37ce371804f", "user_id": "37"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(d522bf11-71f1-4cf9-b0a2-e4451b5e3e30) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(d522bf11-71f1-4cf9-b0a2-e4451b5e3e30) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 123, "email": "hobip27743@nozamas.com", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981586+00:00", "updated_at": "2024-11-26 13:19:59.981587+00:00", "organization_id": "f7245f4e-7b18-4509-a4e5-bb7fd94da239", "project_id": "c0b33d4b-cd41-45c7-a640-a4e6fb0b23d7", "user_id": "38"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(f7245f4e-7b18-4509-a4e5-bb7fd94da239) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(f7245f4e-7b18-4509-a4e5-bb7fd94da239) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 124, "email": "xug36373@inohm.com", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981589+00:00", "updated_at": "2024-11-26 13:19:59.981591+00:00", "organization_id": "8a6673dd-8d8d-4aa9-b772-2a8aac3e8d25", "project_id": "1d2c131d-d418-4a21-83a4-ecc0d9afe970", "user_id": "39"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(8a6673dd-8d8d-4aa9-b772-2a8aac3e8d25) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(8a6673dd-8d8d-4aa9-b772-2a8aac3e8d25) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 125, "email": "shrikishan.mahla@habilelabs.io", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981593+00:00", "updated_at": "2024-11-26 13:19:59.981594+00:00", "organization_id": "dabfdbbc-3a9e-461c-bc50-635a7e49171f", "project_id": "ad257702-53b4-43cc-91a1-6fc11077e99e", "user_id": "40"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(dabfdbbc-3a9e-461c-bc50-635a7e49171f) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(dabfdbbc-3a9e-461c-bc50-635a7e49171f) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 126, "email": "vijayhabilelabs@gmail.com", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981597+00:00", "updated_at": "2024-11-26 13:19:59.981598+00:00", "organization_id": "da3d5a77-453a-4dae-9ce4-24302f05623d", "project_id": "22008d08-29f3-4873-8822-fff9bd30070c", "user_id": "41"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(da3d5a77-453a-4dae-9ce4-24302f05623d) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(da3d5a77-453a-4dae-9ce4-24302f05623d) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 127, "email": "girishchadha.gc@gmail.com", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981600+00:00", "updated_at": "2024-11-26 13:19:59.981601+00:00", "organization_id": "13cc11c9-9b5b-4402-9783-e30bca38cdd2", "project_id": "e4e88ead-93cf-464d-9db9-c5a5a9b3e3e8", "user_id": "42"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(13cc11c9-9b5b-4402-9783-e30bca38cdd2) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(13cc11c9-9b5b-4402-9783-e30bca38cdd2) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 128, "email": "babu.kumawat@habilelabs.io", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981603+00:00", "updated_at": "2024-11-26 13:19:59.981604+00:00", "organization_id": "55955367-2397-4771-abff-d177efe905d8", "project_id": "2e8f8a3b-358a-4988-9f3c-d05057c3455f", "user_id": "44"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(55955367-2397-4771-abff-d177efe905d8) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(55955367-2397-4771-abff-d177efe905d8) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 129, "email": "gaurang.sharma@habilelabs.io", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981606+00:00", "updated_at": "2024-11-26 13:19:59.981607+00:00", "organization_id": "16e27561-4313-4eac-b744-c807e1209cf6", "project_id": "54cc7606-120f-4fa3-bcd7-23f3d354a157", "user_id": "45"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(16e27561-4313-4eac-b744-c807e1209cf6) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(16e27561-4313-4eac-b744-c807e1209cf6) is not present in table \"accounts_organization\".\n\n"}
-----|10
{"failed_row": {"id": 130, "email": "gaurang.sharma@habilelabs.io", "role": "organization owner", "invitation_accepted": true, "assigned_at": "2024-11-26 13:19:59.981609+00:00", "updated_at": "2024-11-26 13:19:59.981610+00:00", "organization_id": "16e27561-4313-4eac-b744-c807e1209cf6", "project_id": "19f3f0cf-8b36-49b0-bd46-cea20e815f41", "user_id": "45"}, "error": "insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(16e27561-4313-4eac-b744-c807e1209cf6) is not present in table \"accounts_organization\".\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 152, in load_data_into_table\n    tar_conn.commit()\npsycopg2.errors.ForeignKeyViolation: insert or update on table \"projects_projectmember\" violates foreign key constraint \"projects_projectmemb_organization_id_7dae7338_fk_accounts_\"\nDETAIL:  Key (organization_id)=(16e27561-4313-4eac-b744-c807e1209cf6) is not present in table \"accounts_organization\".\n\n"}
-----|10
